== Setting up Login Credentials for the Red Hat Container Catalog
Red Hat has recently launched the https://registry.redhat.io[registry.redhat.io] container image registry, which will soon replace https://registry.acccess.redhat.com[registry.access.redhat.com] as the official download source for container images that are both built and supported by Red Hat. The notable difference between these two is that https://registry.redhat.io[registry.redhat.io] requires authentication using your Red Hat account credentials. The Red Hat Container Catalog (of certified third-party ISV images) has this same requirement, which is admittedly a pain since it requires the following extra steps when deploying your application:

. Logging into the target registry using your Red Hat account credentials
. Passing the resulting config.json (docker) or auth.json (podman) file into OpenShift as a secret
. Associating this secret with a service account to use when pulling images
. Repeat the above steps for every project/namespace created in OpenShift

In this post, we'll show how to setup a Red Hat service account for global use in OpenShift when pulling images. This will then be used by all projects/namespaces in OpenShift when logging into the associated registry. In this example, we use the Red Hat Container Catalog (RHCC) as the authenticated registry. To continue, you will need a Red Hat account and an available deployment of OpenShift Container Platform. You will also need root access to all hosts in the cluster in order to run the required Ansible playbook, as well as the original Ansible hosts file used to deploy OpenShift onto the cluster.

The first step is to create your Red Hat service account and token to use for accessing the registry. You can do this by visiting the following console (https://access.redhat.com/terms-based-registry/) and creating a *New Service Account*. This process is mostly self-explanatory, but documentation is available at https://access.redhat.com/RegistryAuthentication if needed.

The next step is to make the necessary changes to your Ansible hosts file that was originally used to install OpenShift. In this case, we'll use the `/etc/ansible/hosts` file on the primary master host, mainly to avoid passing `-i /path/to/hosts/file` when invoking Ansible. Open your hosts file in an editor, and add the `openshift_additional_registry_credentials` variable under the `[OSEv3:vars]` section so that it contains your service account username (including the pipe `|` symbol) and password token:

----
...
[OSEv3:vars]
...
openshift_additional_registry_credentials=[{'host':'registry.connect.redhat.com','user':'12345678|exampleusr','password':'<token_string>','test_image':'mongodb/enterprise-operator:0.3.2'}]
----

You can safely use the `test_image` specified in the above example. Once you've finished editing the hosts file, save/exit the editor and invoke the following Ansible playbook (if not using `/etc/ansible/hosts` then you must pass `-i /path/to/hosts`) :

----
# ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/updates/registry_auth.yml
----

Once the above playbook completes, you'll be able to consume images directly from the Red Hat Container Catalog in Openshift without ever having to create an image-pull secret.
